version: "3.8"
services:
  backend:
    image: "xela1891/springboot-react-fullstack:28.5.2021.21.20.26"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
